-- Catálogo CIE-10 (enfermedades) — enfocado en oftalmología (capítulo H00–H59)
-- más algunas de uso frecuente. El médico puede buscar por código o descripción
-- y cargarlo en el diagnóstico sin escribir a mano.

CREATE TABLE IF NOT EXISTS cie10 (
  codigo      VARCHAR(10) PRIMARY KEY,
  descripcion TEXT NOT NULL
);

INSERT INTO cie10 (codigo, descripcion) VALUES
  ('H00.0', 'Orzuelo (hordeolo) y otras inflamaciones profundas del párpado'),
  ('H00.1', 'Chalazión'),
  ('H01.0', 'Blefaritis'),
  ('H02.0', 'Entropión y triquiasis palpebral'),
  ('H02.1', 'Ectropión palpebral'),
  ('H02.4', 'Ptosis del párpado'),
  ('H04.1', 'Ojo seco (síndrome del ojo seco)'),
  ('H04.2', 'Epífora (lagrimeo excesivo)'),
  ('H04.3', 'Dacriocistitis aguda'),
  ('H10.0', 'Conjuntivitis mucopurulenta'),
  ('H10.1', 'Conjuntivitis atópica aguda'),
  ('H10.3', 'Conjuntivitis aguda, no especificada'),
  ('H10.4', 'Conjuntivitis crónica'),
  ('H10.9', 'Conjuntivitis, no especificada'),
  ('H11.0', 'Pterigión'),
  ('H11.1', 'Pinguécula (degeneración conjuntival)'),
  ('H11.3', 'Hemorragia conjuntival'),
  ('H16.0', 'Úlcera de la córnea'),
  ('H16.1', 'Queratitis superficial'),
  ('H16.9', 'Queratitis, no especificada'),
  ('H18.6', 'Queratocono'),
  ('H20.0', 'Iridociclitis aguda (uveítis anterior)'),
  ('H25.0', 'Catarata senil incipiente'),
  ('H25.1', 'Catarata senil nuclear'),
  ('H25.2', 'Catarata senil, tipo morgagnian'),
  ('H25.9', 'Catarata senil, no especificada'),
  ('H26.0', 'Catarata infantil, juvenil y presenil'),
  ('H26.4', 'Catarata secundaria'),
  ('H26.9', 'Catarata, no especificada'),
  ('H27.0', 'Afaquia (ausencia del cristalino)'),
  ('H33.0', 'Desprendimiento de retina con ruptura'),
  ('H33.2', 'Desprendimiento seroso de la retina'),
  ('H33.5', 'Otros desprendimientos de la retina'),
  ('H34.1', 'Oclusión de la arteria central de la retina'),
  ('H34.8', 'Oclusión de la vena central de la retina'),
  ('H35.0', 'Retinopatía del fondo y cambios vasculares retinianos'),
  ('H35.3', 'Degeneración macular relacionada con la edad (DMAE)'),
  ('H35.8', 'Otros trastornos especificados de la retina'),
  ('H36.0', 'Retinopatía diabética'),
  ('H40.0', 'Sospecha de glaucoma / hipertensión ocular'),
  ('H40.1', 'Glaucoma primario de ángulo abierto'),
  ('H40.2', 'Glaucoma primario de ángulo cerrado'),
  ('H40.9', 'Glaucoma, no especificado'),
  ('H43.1', 'Hemorragia del vítreo'),
  ('H43.9', 'Trastorno del cuerpo vítreo, no especificado'),
  ('H44.0', 'Endoftalmitis purulenta'),
  ('H46',   'Neuritis óptica'),
  ('H47.0', 'Trastornos del nervio óptico, no clasificados en otra parte'),
  ('H49.9', 'Estrabismo paralítico, no especificado'),
  ('H50.0', 'Estrabismo convergente (esotropía)'),
  ('H50.1', 'Estrabismo divergente (exotropía)'),
  ('H52.0', 'Hipermetropía'),
  ('H52.1', 'Miopía'),
  ('H52.2', 'Astigmatismo'),
  ('H52.4', 'Presbicia'),
  ('H53.1', 'Alteraciones visuales subjetivas'),
  ('H53.4', 'Defectos del campo visual'),
  ('H54.0', 'Ceguera de ambos ojos'),
  ('H54.9', 'Disminución de la agudeza visual, no especificada'),
  ('H57.1', 'Dolor ocular'),
  ('H57.9', 'Trastorno del ojo y sus anexos, no especificado'),
  ('H10.5', 'Blefaroconjuntivitis'),
  ('H18.4', 'Degeneración de la córnea'),
  ('H25.8', 'Otras cataratas seniles'),
  ('E11.3', 'Diabetes mellitus tipo 2 con complicaciones oftálmicas'),
  ('I10',   'Hipertensión esencial (primaria)')
ON CONFLICT (codigo) DO NOTHING;
